/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgotpass_screen` | `/forgotpass_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login_screen` | `/login_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup_screen` | `/signup_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/preview_screen` | `/preview_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/splash_screen` | `/splash_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home_screen` | `/home_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile_screen` | `/profile_screen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/forgotpass_screen` | `/forgotpass_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login_screen` | `/login_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup_screen` | `/signup_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(splash)'}/preview_screen` | `/preview_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(splash)'}/splash_screen` | `/splash_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(splash)'}/styles` | `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home_screen` | `/home_screen`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile_screen` | `/profile_screen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/forgotpass_screen${`?${string}` | `#${string}` | ''}` | `/forgotpass_screen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login_screen${`?${string}` | `#${string}` | ''}` | `/login_screen${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup_screen${`?${string}` | `#${string}` | ''}` | `/signup_screen${`?${string}` | `#${string}` | ''}` | `${'/(splash)'}/preview_screen${`?${string}` | `#${string}` | ''}` | `/preview_screen${`?${string}` | `#${string}` | ''}` | `${'/(splash)'}/splash_screen${`?${string}` | `#${string}` | ''}` | `/splash_screen${`?${string}` | `#${string}` | ''}` | `${'/(splash)'}/styles${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home_screen${`?${string}` | `#${string}` | ''}` | `/home_screen${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile_screen${`?${string}` | `#${string}` | ''}` | `/profile_screen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/forgotpass_screen` | `/forgotpass_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login_screen` | `/login_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup_screen` | `/signup_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/preview_screen` | `/preview_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/splash_screen` | `/splash_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(splash)'}/styles` | `/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home_screen` | `/home_screen`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile_screen` | `/profile_screen`; params?: Router.UnknownInputParams; };
    }
  }
}
